[workspace]
members = [
    "assignments/assignment1",
    "assignments/assignment2", 
    "assignments/assignment3",
    "assignments/shared",
    "capstone"
]

[workspace.package]
edition = "2021"

[dependencies]
chrono = "0.4.23"
