[workspace]
members = [
    "assignments/assignment1",
    "assignments/assignment2", 
    "assignments/assignment3",
    "assignments/shared",
    "backend",
    "capstone"
]

[workspace.package]
edition = "2021"